name: ps-ci
on:
  push:
    branches: [ main ]
    paths:
      - "scripts/**/*.ps1"
      - ".github/workflows/powershell-ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/**/*.ps1"
      - ".github/workflows/powershell-ci.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force -SkipPublisherCheck
      - name: Lint scripts
        shell: pwsh
        run: |
          if (-not (Test-Path 'scripts')) { Write-Host "No scripts dir. Skipping."; exit 0 }
          Invoke-ScriptAnalyzer -Path 'scripts' -Recurse -Severity Information,Warning,Error
